server:
  port: 13001
spring:
  profiles:
    include: sharding
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.108:3306/gmall_order?useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
#  rabbitmq:
#    username: admin
#    password: admin
#    host: 192.168.2.108
#    port: 5672
#    virtual-host: /
#    publisher-returns: true # 发布者返回（消息成功标志）
#    publisher-confirm-type: simple #开启发布者简单确认机制
#    listener: #监听器帮我们拿到消息。默认自动ack
#      type: simple
#      simple:
#        acknowledge-mode: manual #开启手动确认机制，除非程序员自己ack，否则服务器都认为消息还未回复
#        batch-size: 12

app:
  ware-url: http://localhost:9001/

feign:
  sentinel:
    enabled: true
