server:
  port: 11001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.108:3306/gmall_user?useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
