server:
  port: 9000
spring:
  zipkin:
    base-url: http://192.168.2.108:9411/
    sender:
      type: web

    # 数据源配置好
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.108:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 192.168.2.108
    password: Lfy123456


app:
  minio:
    endpoint: http://192.168.2.108:9000  # 访问minio的地址
    ak: admin   # 用户名
    sk: admin123456 # 密码
    bucketName: gmall # 桶名
  thread-pool:
    core: 4
    max: 8
